# Generated by Django 4.2.5 on 2023-10-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('tags', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=150)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('favicon', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('color_status', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
