# Generated by Django 4.2.5 on 2023-10-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='release_date',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=1, upload_to='films/'),
            preserve_default=False,
        ),
    ]
