# Generated by Django 4.2.5 on 2023-10-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
