# Generated by Django 4.2.5 on 2023-10-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
