# Generated by Django 4.2.5 on 2023-10-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_imagegallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
