# Generated by Django 4.2.5 on 2023-10-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_articles_category'),
        ('home', '0007_newsuseremail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
