# Generated by Django 4.2.5 on 2023-10-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_articles_alter_imagegallery_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
